### ISSUE TITLE
Can't create component 'CP.MultiTenancy.TenantManager' as it has dependencies to be satisfied

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#124]
in application service i have a method to create a tenant and additional entities under the created tenant, i user tenant repository not tenant manager
All code in that method is executed with no problem, and all entities are saved to database, but in angular application i catch an error, and also logged in database.  
 
```
Castle.MicroKernel.Handlers.HandlerException: Can't create component 'CP.MultiTenancy.TenantManager' as it has dependencies to be satisfied.

'CP.MultiTenancy.TenantManager' is waiting for the following dependencies:
- Service 'Abp.Application.Editions.AbpEditionManager' which was not registered.

   at Castle.MicroKernel.Handlers.DefaultHandler.AssertNotWaitingForDependency()
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, IDictionary additionalArguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, IDictionary arguments)
   at Castle.Windsor.WindsorContainer.Resolve(Type service)
   at Abp.Dependency.IocManager.Resolve(Type type)
   at Abp.Events.Bus.Factories.IocHandlerFactory.GetHandler()
   at Abp.Events.Bus.EventBus.Trigger(Type eventType, Object eventSource, IEventData eventData)
   at Abp.Events.Bus.EventBus.Trigger(Type eventType, IEventData eventData)
   at Abp.Events.Bus.Entities.EntityChangedEventHelper.<>c__DisplayClass1.<TriggerEntityChangeEvent>b__0(Object sender, EventArgs args)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Abp.Extensions.EventHandlerExtensions.InvokeSafely(EventHandler eventHandler, Object sender, EventArgs e)
   at Abp.Extensions.EventHandlerExtensions.InvokeSafely(EventHandler eventHandler, Object sender)
   at Abp.Domain.Uow.UnitOfWorkBase.OnCompleted()
   at Abp.Domain.Uow.UnitOfWorkBase.<CompleteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Abp.Domain.Uow.UnitOfWorkInterceptor.<>c__DisplayClass8.<<PerformAsyncUow>b__2>d__d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Abp.Threading.InternalAsyncHelper.<AwaitTaskWithPostActionAndFinallyAndGetResult>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Abp.Threading.InternalAsyncHelper.<AwaitTaskWithFinallyAndGetResult>d__c`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Abp.Extensions.ExceptionExtensions.ReThrow(Exception exception)
   at Abp.WebApi.Controllers.Dynamic.Selectors.DynamicHttpActionDescriptor.<ExecuteAsync>b__0(Task`1 ta
```

The TenantManager Class is only used in the service base class "CPAppServiceBase" and i don't use that class

**Comment by hikalkan** [comment]
Hi @emaish,
Create EditionManager class for your application (in the Domain layer) as described in release notes: https://github.com/aspnetboilerplate/module-zero/releases/tag/v0.7.2.0

**Comment by emaish** [comment]
sorry, i didn't read the release for this version, i created EditionManager and changed TenantManager constructor from AbpEditionManager to EditionManager, it's working now.
Thank you,
