### ISSUE TITLE
Aspnetboiler plate module zero sample project and database problem

### ISSUE THREAD

**Issue by visuallemon** [aspnetboilerplate/module-zero#23]
Hello,

Trying to get up and running module-zero sample project here.

System: 
Windows 8
MySQL 5.6
Entity Framework 6
Visual Studio 2012

Don't know what else to post, please let me know if you need something.

When i run "update-database" command on package management console i get error below.
Wondering if this is a bug or MySql support issue with the sample project.
I'm quite new with entity framework.
All the tables was created properly, but it looks like it has problems writing data in the database.

Maybe you guys could help me to solve this? 
```
PM> update-database
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
No pending explicit migrations.
System.Data.Entity.Core.MetadataException: Schema specified is not valid. Errors: 
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
   at System.Data.Entity.Core.Metadata.Edm.StoreItemCollection.Loader.ThrowOnNonWarningErrors()
   at System.Data.Entity.Core.Metadata.Edm.StoreItemCollection.Loader.LoadItems(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths)
   at System.Data.Entity.Core.Metadata.Edm.StoreItemCollection.Loader..ctor(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths, Boolean throwOnError, IDbDependencyResolver resolver)
   at System.Data.Entity.Core.Metadata.Edm.StoreItemCollection.Init(IEnumerable`1 xmlReaders, IEnumerable`1 filePaths, Boolean throwOnError, IDbDependencyResolver resolver, DbProviderManifest& providerManifest, DbProviderFactory& providerFactory, String& providerInvariantName, String& providerManifestToken, Memoizer`2& cachedCTypeFunction)
   at System.Data.Entity.Core.Metadata.Edm.StoreItemCollection..ctor(IEnumerable`1 xmlReaders)
   at System.Data.Entity.Utilities.XDocumentExtensions.GetStorageMappingItemCollection(XDocument model, DbProviderInfo& providerInfo)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.Diff(XDocument sourceModel, XDocument targetModel, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator, String sourceModelVersion, String targetModelVersion)
   at System.Data.Entity.Migrations.DbMigrator.IsModelOutOfDate(XDocument model, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.<Update>b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update(String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Schema specified is not valid. Errors: 
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type nvarchar(max) is not qualified with a namespace or alias. Only primitive types can be used without qualification.
```
This is app.config from EntityFramework project
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 --></configSections>
  <connectionStrings>
    <add name="Default" providerName="MySql.Data.MySqlClient" connectionString="
         server=localhost; 
         port=3306;
         database=modulezerosampleproject;
         uid=root;
         password=testpassword" />
  </connectionStrings>

  <entityFramework codeConfigurationType="MySql.Data.Entity.MySqlEFConfiguration, MySql.Data.Entity.EF6">
    <defaultConnectionFactory type="MySql.Data.Entity.MySqlConnectionFactory, MySql.Data.Entity.EF6" />
    <providers>
      <provider invariantName="MySql.Data.MySqlClient" type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6" />
    </providers>
  </entityFramework>
<system.data>
    <DbProviderFactories>
      <remove invariant="MySql.Data.MySqlClient" />
      <add name="MySQL Data Provider" invariant="MySql.Data.MySqlClient" description=".Net Framework Data Provider for MySQL" type="MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data, Version=6.9.5.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d" />
    </DbProviderFactories>
  </system.data>
</configuration>
```

**Comment by jaq316** [comment]
Just for reference: There is an unanswered question regarding this on [StackOverflow] (http://stackoverflow.com/questions/22262817/mysql-5-6-with-entityframework-6-schema-error-0040).

**Comment by visuallemon** [comment]
Yes and looks like people still getting same issue. Would appreciate any help on this one. Thank you.

**Comment by hikalkan** [comment]
Hi,

Actually, I did not worked EF & MySQL before. But, I guess this issue is not related to ABP.

**Comment by hmmdeif** [comment]
For MySql configurations, putting `SetSqlGenerator("MySql.Data.MySqlClient", new MySqlMigrationSqlGenerator());` in the Configuration class in EntityFramework proj. Otherwise EF will just generate MSSQL (thus all your namespacing errors).

**Comment by kilkfoe** [comment]
@hmmdeif I already have this in my configuration file and my situation is identical to the question (same specs, same code, same error messages)

My configuration constructor looks like:
<code>
public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            SetSqlGenerator("MySql.Data.MySqlClient", new MySql.Data.Entity.MySqlMigrationSqlGenerator());
            CodeGenerator = new MySql.Data.Entity.MySqlMigrationCodeGenerator();
        }
</code>

**Comment by hmmdeif** [comment]
@kilkfoe Hmm ok that's weird. The only thing different on my setup is I don't have the CodeGenerator variable set (just `SetSqlGenerator`). Everything looks identical to my setup and I have it running and migrating fine on MySql. What are your web and app.configs (web in .Web proj and app in .EntityFramework proj). I doubt it will make a difference but it was such a pain for me to get MySql up and running with EF.

**Comment by kilkfoe** [comment]
All my entity framework configuration is currently in my web.config while I'm looking at how to separate it in to its own tier. Sorry for the weird formatting below I haven't figured out how to separate the lines of code on this forum yet.

<code>
&lt;system.data&gt;
    &lt;DBProviderFactories&gt;
      &lt;clear /&gt;
      &lt;remove invariant=&quot;MySql.Data.MySqlClient&quot;/&gt;
      &lt;add name=&quot;MySql.Data.MySqlClient&quot; invariant=&quot;MySql.Data.MySqlClient&quot; description=&quot;.Net Framework Data Provider for MySQL&quot; type=&quot;MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data,Version=6.9.5.0, Culture=neutral,PublicKeyToken=c5687fc88969c44d&quot;/&gt;
    &lt;/DBProviderFactories&gt;
  &lt;/system.data&gt;
</code>

<code>
  &lt;entityFramework codeConfigurationType=&quot;MySql.Data.Entity.MySqlEFConfiguration, MySql.Data.Entity.EF6&quot;&gt;
    &lt;defaultConnectionFactory type=&quot;MySql.Data.Entity.MySqlConnectionFactory, MySql.Data.Entity.EF6&quot; /&gt;
    &lt;providers&gt;
      &lt;provider invariantName=&quot;MySql.Data.MySqlClient&quot; type=&quot;MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6&quot; /&gt;
    &lt;/providers&gt;
  &lt;/entityFramework&gt;
</code>

**Comment by kilkfoe** [comment]
I actually got it working past this error simply by updating the entity framework nuget package. I am still having an issue where the generated script for downgrading database versions is naming a constraint incorrectly. Instead of using the correct name it uses 'FK_{guid}' where {guid} is some guid value I don't know where the guid value came from.

This is a much smaller issue which can be tested and fixed on each release as long as I manually run the update scripts, so it's good enough for now.

**Comment by brendan-rice** [comment]
That second issue you mentioned still sounds like an entity framework issue. StackOverflow might be a better option for asking about it.

**Comment by kilkfoe** [comment]
Yeah I actually just figured out that it's a bug with MySQL and Entity Framework. I said it backwards before. When foreign key constraint names are too long it shortens them by using FK_Guid (I assume it does this for any name too long). However, it doesn't use that same Guid on the DOWN method - it still uses the long constraint name, which doesn't exist.

**Comment by Jesn** [comment]
@mkmita   I want to convert ABP from sqlserver to MySQL, what should I do?
