### ISSUE TITLE
No IUserTokenProvider is registered

### ISSUE THREAD

**Issue by gabrielrobert** [aspnetboilerplate/module-zero#263]
@hikalkan I'm still having issue with the IUserTokenProvider, is there a way to handle this?

```
System.NotSupportedException: No IUserTokenProvider is registered.
   at Microsoft.AspNet.Identity.UserManager`2.<GenerateUserTokenAsync>d__fe.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestProject.Web.Controllers.AccountController.<Register>d__13.MoveNext() in C:\dev\TestProject\src\TestProject.Web\Controllers\AccountController.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
```

Somewhere in Configure(IApplicationBuilder app):

```
public void Configure(IApplicationBuilder app)
        {
            app.UseDeveloperExceptionPage();
            app.UseDatabaseErrorPage();
            app.UseAbp();

            AuthConfigurer.Configure(app, _appConfiguration);

            app.UseStaticFiles();

            app.UseAppBuilder(ConfigureOwinServices);

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "defaultWithArea",
                    template: "{area}/{controller=Home}/{action=Index}/{id?}");

                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            Clock.Provider = ClockProviders.Utc;
        }
```

Then:

```
private static void ConfigureOwinServices(IAppBuilder app)
        {
            app.Properties["host.AppName"] = "TestProject";
            app.UseAbp();
            app.RegisterDataProtectionProvider();
        }
```

```
[DependsOn(
         typeof(TestProjectApplicationModule),
         typeof(TestProjectEntityFrameworkCoreModule),
        typeof(AbpZeroOwinModule),
         typeof(AbpAspNetCoreModule),
         typeof(AbpAutoMapperModule))]
    public class TestProjectWebModule : AbpModule
```

**Comment by gabrielrobert** [comment]
Is there any way I can get around this problem before it's fixed? I'm ready to go in production with my application, but still missing registration part.

**Comment by hikalkan** [comment]
You are using it with AspNet Core. We haven't tried it with AspNet Core before. AspNet Core'a OWIN integration is simple, thus there may be some missing parts.

When I check ASP.NET Identity's source code (with decompiling), I see this:

````C#
public static IDataProtectionProvider GetDataProtectionProvider(this IAppBuilder app)
{
    if (app == null)
    throw new ArgumentNullException("app");
    object obj;
    if (app.Properties.TryGetValue("security.DataProtectionProvider", out obj))
    {
    Func<string[], Tuple<Func<byte[], byte[]>, Func<byte[], byte[]>>> create = obj as Func<string[], Tuple<Func<byte[], byte[]>, Func<byte[], byte[]>>>;
    if (create != null)
        return (IDataProtectionProvider) new AppBuilderExtensions.CallDataProtectionProvider(create);
    }
    return (IDataProtectionProvider) null;
}
````

So, it gets an object with key "security.DataProtectionProvider" from app.Properties. Probably AspNet Core does not implement this.

I think we have 2 options;

* We can somehow get DataProtectionProvider of AspNet Core (I don't know if there is one).
* We can implement IDataProtectionProvider interface ourselves. Simplest implementation would be returning same data from Protect and Unprotect methods.
