### ISSUE TITLE
Issue while using AbpUserManager<Role, User>to set roles for user

### ISSUE THREAD

**Issue by HossamZaki** [aspnetboilerplate/module-zero#269]
I am facing an issue while trying to use userManager : AbpUserManager<Role, User> to set roles to user 
this is a sample of my code:
```
 var user = await userManager.GetUserByIdAsync(input.UserId);
                  string[] roles = input.UserRolesNames.ToArray();
                  await userManager.SetRoles(user, roles); 
```

this is the error I am getting:
```Value cannot be null.
Parameter name: source```

```
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Abp.Authorization.Users.AbpUserManager`2.<SetRoles>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

Is there any way I can avoid this error?

**Comment by hikalkan** [comment]
Hi,

This is because user.Roles is null. Normally, it should be lazy loaded and can not be null.
Are you running this code is a Unit Of Work? For example, are you running inside an application service method? Also, which version of ABP you're using?

**Comment by HossamZaki** [comment]
yes lazy loading was disabled.

Thanks a lot for the fast response
