### ISSUE TITLE
UpdateSecurityStampAsync UserId Not Found

### ISSUE THREAD

**Issue by cuibty** [aspnetboilerplate/module-zero#283]
```
System.InvalidOperationException: UserId not found.
   at Microsoft.AspNet.Identity.UserManager`2.<UpdateSecurityStampAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Snowflake.Web.Controllers.AccountController.<Login>d__10.MoveNext() in C:\Users\cuibty\Desktop\Snowflake\Snowflake.Web\Controllers\AccountController.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

```

**Comment by hikalkan** [comment]
This generally happens in a multi-tenant application. where you forget to set user's tenant to current unit of work. Be sure that AbpSession.TenantId is same as user's tenant id or manually set tenant id for current unit of work (http://www.aspnetboilerplate.com/Pages/Documents/Multi-Tenancy#switching-between-host-and-tenants)

**Comment by cuibty** [comment]
thanks!

UpdateSecurityStampAsync does not work

**UserManager.ChangePasswordAsync()** or manual call **UpdateSecurityStampAsync** method

Startup.cs
~~~
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
    LoginPath = new PathString("/Account/Login"),
    Provider = new CookieAuthenticationProvider
    {
        OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<UserManager<User, long>, User, long>(
            validateInterval: TimeSpan.FromMinutes(0),
            regenerateIdentityCallback: (manager, user) => user.GenerateUserIdentityAsync(manager),
            getUserIdCallback: id => id.GetUserId<long>()
        )
    }
});
~~~

User.cs
~~~
public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<User, long> manager)
{
    var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
    return userIdentity;
}
~~~

**Comment by psyvision** [comment]
@cubity the above code is pretty much what I use.  Although we don't use a multi-tenant scenario so @hikalkan assumption sounds about correct.  I would presume that you need to set the current tenant as part of the regenerateIdentityCallback or when generating the identity.

**Comment by hikalkan** [comment]
This worked for me:

````C#
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
    LoginPath = new PathString("/Account/Login"),
    Provider = new CookieAuthenticationProvider
    {
        OnValidateIdentity = async context =>
        {
            var tenantId = context.Identity.GetTenantId();

            using (var uowManager = IocManager.Instance.ResolveAsDisposable<IUnitOfWorkManager>())
            {
                using (var uow = uowManager.Object.Begin())
                {
                    using (uowManager.Object.Current.SetTenantId(tenantId))
                    {
                        await (SecurityStampValidator.OnValidateIdentity<UserManager, User, long>(
                                validateInterval: TimeSpan.FromMinutes(0),
                                regenerateIdentityCallback: (manager, user) => manager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie),
                                getUserIdCallback: id => id.GetUserId<long>()
                            ))(context);

                        await uowManager.Object.Current.SaveChangesAsync();
                    }

                    await uow.CompleteAsync();
                }
            }
        }
    }
});
````

But notice that it makes a few database operation in every request, that causes a performance loss.

**Comment by Worthy7** [comment]
Hmm, can these be put into a cache @hikalkan ? It makes sense to have them be checked every time a user   makes a request but of course it will slow down every request. So can It be cached some how for the last 10 minutes or so for any user? (I don't know how caching in ABP works yet)

**Comment by hikalkan** [comment]
You can use ABP's caching to improve it.
