### ISSUE TITLE
LoginManager.LoginAsync throws error for 2.0.0

### ISSUE THREAD

**Issue by gabrielrobert** [aspnetboilerplate/module-zero#344]
As part of 1.5.2, I was using this code to login users:

```
var loginResult = await _loginManager.LoginAsync(model.Username, model.Password, "");
await SignInAsync(loginResult.User, loginResult.Identity, model.RememberMe);
```

However, for some reason this is not working anymore.

```
Mvc.ExceptionHandling.AbpExceptionFilter - Value cannot be null.
Parameter name: user
System.ArgumentNullException: Value cannot be null.
Parameter name: user
   at Microsoft.AspNet.Identity.UserManager`2.CreateIdentityAsync(TUser user, String authenticationType)
   at Abp.Authorization.Users.AbpUserManager`2.<CreateIdentityAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestProject.Web.Controllers.AccountController.<SignInAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TestProject.Web.Controllers.AccountController.<Login>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
```

Any idea? I look at ABP code, and nothing seems wrong.

**Comment by hikalkan** [comment]
You should normally check loginResult.Result property and SignIn only if it's succeed. Can you check it? If it's not succeed, User will be null which causes the exception.

**Comment by gabrielrobert** [comment]
@hikalkan The exception is thrown in  `await _loginManager.LoginAsync(model.Username, model.Password, "")` method, I cannot access loginResult unfortunately.

**Comment by acjh** [comment]
Your stack trace says it's thrown in `TestProject.Web.Controllers.AccountController.<SignInAsync>`.

**Comment by gabrielrobert** [comment]
@acjh You're right, sorry. However, the result is: `Abp.Authorization.AbpLoginResultType.InvalidUserNameOrEmailAddress`

I'm using the same user / password used before migration. Is there any configuration about username / password that I need to setup? I know my credentials are valid.

**Comment by gabrielrobert** [comment]
Ok, I found it. This code was working with old version, because it was not checking any tenancy in the database:

`await _loginManager.LoginAsync(model.Username, model.Password, "")`

With 2.0.0, the generated SQL query is:

```
SELECT
	"e"."Id",
	"e"."AccessFailedCount",
	"e"."AuthenticationSource",
	"e"."CreationTime",
	"e"."CreatorUserId",
	"e"."DeleterUserId",
	"e"."DeletionTime",
	"e"."EmailAddress",
	"e"."EmailConfirmationCode",
	"e"."IsActive",
	"e"."IsDeleted",
	"e"."IsEmailConfirmed",
	"e"."IsLockoutEnabled",
	"e"."IsPhoneNumberConfirmed",
	"e"."IsTwoFactorEnabled",
	"e"."LastLoginTime",
	"e"."LastModificationTime",
	"e"."LastModifierUserId",
	"e"."LockoutEndDateUtc",
	"e"."Name",
	"e"."Password",
	"e"."PasswordResetCode",
	"e"."PhoneNumber",
	"e"."SecurityStamp",
	"e"."Surname",
	"e"."TenantId",
	"e"."UserName"
FROM
	"AbpUsers" AS "e"
WHERE
	(
		"e"."TenantId" IS NULL
		AND ("e"."IsDeleted" = FALSE)
	)
AND (
	(
		"e"."UserName" = @__userNameOrEmailAddress_1
	)
	OR (
		"e"."EmailAddress" = @__userNameOrEmailAddress_2
	)
)
```
It's problematic, because it checks if "TenantId IS NULL".


@hikalkan  Is there any way to ignore tenancy in this request? I want to be able to login without the tenancy name.

**Comment by acjh** [comment]
You need `tenancyName` because `UserName` is only [unique for a tenant by design](https://aspnetboilerplate.com/Pages/Documents/Zero/User-Management).

If you assume `UserName` is unique across tenants, you can do this:
```c#
int? tenantId;
using (CurrentUnitOfWork.DisableFilter(AbpDataFilters.MayHaveTenant))
{
    var user = await _userManager.FindByNameAsync(model.Username);
    tenantId = user.TenantId;
}
var tenant = tenantId.HasValue ? await _tenantManager.GetByIdAsync(tenantId.Value) : null;
var loginResult = await _loginManager.LoginAsync(model.Username, model.Password, tenant?.TenancyName);
```
