### ISSUE TITLE
Migration problem with MySQL

### ISSUE THREAD

**Issue by falps** [aspnetboilerplate/module-zero#394]
Hi I'm attempting to use the latest Migrator to create some new MySQL migrations .I have a project EFcore+Jquery+netcore  (just downloaded today).Have all the necessary MySQL dependencies, connection string and DbContextConfigurer wired.
Builds fine. But...
I get the following when attempting a run after cleaning all of my EntityFramework migrations:
System.InvalidOperationException: The entity type 'EditionFeatureSetting' is part of a hierarchy, but does not have a discriminator property configured.
   at Microsoft.EntityFrameworkCore.Internal.ModelValidator.ShowError(String message)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.ValidateDiscriminator(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.ValidateDiscriminatorValues(IEntityType rootEntityType)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.ValidateInheritanceMapping(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()

Regards

**Comment by ismcagdas** [comment]
See https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2267#issuecomment-312299633

**Comment by falps** [comment]
Thank you
